# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:empty:
version: 2.1
jobs:
  present_token:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: prepare
          command: apt-update && apt install -y jq
      - run:
        JWT=$CIRCLE_OIDC_TOKEN
        T=$(echo "$JWT" | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson')
        echo "$T" | jq
workflows:
  example:
    jobs:
      - present_token
